name: test
# either manually started, or on a schedule
on: [ push, workflow_dispatch ]
jobs:
  test:
    # ubuntu
    runs-on: ubuntu-latest
    steps:
    # need the repo checked out
    - name: checkout repo
      uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: test
      run: nix-shell --pure --run "make test"
    - name: lint
      run: nix-shell --run "make lint"
